# Generated by Django 5.1.6 on 2025-12-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
